language: swift
xcode_workspace: EosioSwift.xcworkspace
xcode_scheme: EosioSwiftTests
osx_image: xcode10.2
xcode_destination: platform=iOS Simulator,OS=11.4,name=iPhone5s
before_install:
- pod repo update
- pod install